-- insPlayers.sql
INSERT INTO Player (PlayerName, isCaptain)
VALUES
('Olga Carmona', TRUE),
('Kosovare Asllani', TRUE),
('Sam Kerr', TRUE),
('Olga Carmona', TRUE),
('Steph Catley', TRUE),
('Millie Bright', TRUE),
('Esther Gonzalez', TRUE),
('Saki Kumagai', TRUE),
('Catalina Usme', TRUE),
('Wendie Renard', TRUE),
('Millie Bright', TRUE),
('Steph Catley', TRUE),
('Sherida Spitse', TRUE),
('Kosovare Asllani', TRUE),
('Lia Walti', TRUE),
('Saki Kumagai', TRUE),
('Ghizlane Chebbak', TRUE),
('Kim Hye-ri', TRUE),
('Thembi Kgatlana', TRUE),
('Vanina Correa', TRUE),
('Khadija Shaw', TRUE),
('Marta Cox', TRUE),
('Pham Hai Yen', TRUE),
('Dolores Silva', TRUE),
('Nerilia Mondesir', TRUE),
('Wang Shanshan', TRUE),
('Saki Kumagai', TRUE),
('Katherine Alvarado', TRUE),
('Katie McCabe', TRUE),
('Christine Sinclair', TRUE),
('Kim Hye-ri', TRUE),
('Lia Walti', TRUE),
('Maren Mjelde', TRUE),
('Alexandra Popp', TRUE),
('Kosovare Asllani', TRUE),
('Wendie Renard', TRUE),
('Marta Cox', TRUE),
('Vanina Correa', TRUE),
('Millie Bright', TRUE),
('Wang Shanshan', TRUE),
('Lindsey Horan', TRUE),
('Ana Borges', TRUE),
('Steph Catley', TRUE),
('Saki Kumagai', TRUE),
('Ivana Andres', TRUE),
('Jessie Fleming', TRUE),
('Daniela Montoya', TRUE),
('Ria Percival', TRUE),
('Lia Walti', TRUE),
('Barbara Bonansea', TRUE),
('Alexandra Popp', TRUE),
('Rafaelle', TRUE),
('Kosovare Asllani', TRUE),
('Sherida Spitse', TRUE),
('Wendie Renard', TRUE),
('Lindsey Horan', TRUE),
('Barbra Banda', TRUE),
('Millie Bright', TRUE),
('Pernille Harder', TRUE),
('Chiamaka Nnadozie', TRUE),
('Hali Long', TRUE),
('Ivana Andres', TRUE),
('Ali Riley', TRUE),
('Steph Catley', TRUE),
('Megan Rapinoe', TRUE),
('Steph Houghton', TRUE),
('Sari van Veenendaal', TRUE),
('Steph Houghton', TRUE),
('Sara Gama', TRUE),
('Alexandra Popp', TRUE),
('Amandine Henry', TRUE),
('Maren Mjelde', TRUE),
('Sara Gama', TRUE),
('Sari van Veenendaal', TRUE),
('Irene Paredes', TRUE),
('Caroline Seger', TRUE),
('Steph Houghton', TRUE),
('Amandine Henry', TRUE),
('Alexandra Popp', TRUE),
('Maren Mjelde', TRUE),
('Sari van Veenendaal', TRUE),
('Gabrielle Onguene', TRUE),
('Caroline Seger', TRUE),
('Kanjana Sungngoen', TRUE),
('Saki Kumagai', TRUE),
('Rachel Corsie', TRUE),
('Sara Gama', TRUE),
('Konya Plummer', TRUE),
('Janine van Wyk', TRUE),
('Wu Haiyan', TRUE),
('Cho So-hyun', TRUE),
('Desire Oparanozie', TRUE),
('Caroline Seger', TRUE),
('Carli Lloyd', TRUE),
('Sari van Veenendaal', TRUE),
('Christine Sinclair', TRUE),
('Saki Kumagai', TRUE),
('Konya Plummer', TRUE),
('Steph Houghton', TRUE),
('Sam Kerr', TRUE),
('Janine van Wyk', TRUE),
('Desire Oparanozie', TRUE),
('Alexandra Popp', TRUE),
('Amandine Henry', TRUE),
('Ali Riley', TRUE),
('Christiane Endler', TRUE),
('Megan Rapinoe', TRUE),
('Estefania Banini', TRUE),
('Christine Sinclair', TRUE),
('Sam Kerr', TRUE),
('Monica', TRUE),
('Steph Houghton', TRUE),
('Alexandra Popp', TRUE),
('Marta Torrejon', TRUE),
('Maren Mjelde', TRUE),
('Amandine Henry', TRUE),
('Carli Lloyd', TRUE),
('Nadine Angerer', TRUE),
('Aya Miyama', TRUE),
('Carli Lloyd', TRUE),
('Lisa De Vanna', TRUE),
('Steph Houghton', TRUE),
('Nadine Angerer', TRUE),
('Wu Haiyan', TRUE),
('Aya Miyama', TRUE),
('Trine Ronning', TRUE),
('Abby Wambach', TRUE),
('Marta', TRUE),
('Christine Sinclair', TRUE),
('Wendie Renard', TRUE),
('Nadine Angerer', TRUE),
('Wu Haiyan', TRUE),
('Shirley Cruz', TRUE),
('Steph Houghton', TRUE),
('Nayeli Rangel', TRUE),
('Cho So-hyun', TRUE),
('Martina Moser', TRUE),
('Ligia Moreira', TRUE),
('Evelyn Nwabuoku', TRUE),
('Lisa De Vanna', TRUE),
('Duangnapa Sritala', TRUE),
('Fatou Coulibaly', TRUE),
('Wu Haiyan', TRUE),
('Mandy van den Berg', TRUE),
('Wendie Renard', TRUE),
('Marta', TRUE),
('Steph Houghton', TRUE),
('Cho So-hyun', TRUE),
('Lisa De Vanna', TRUE),
('Caroline Abbe', TRUE),
('Aya Miyama', TRUE),
('Carli Lloyd', TRUE),
('Wu Haiyan', TRUE),
('Nadine Angerer', TRUE),
('Dominique Thiamale', TRUE),
('Christine Sinclair', TRUE),
('Wendie Renard', TRUE),
('Veronica Boquete', TRUE),
('Natalia Gaitan', TRUE),
('Marta', TRUE),
('Caroline Seger', TRUE),
('Christine Manie', TRUE),
('Abby Wambach', TRUE),
('Aya Miyama', TRUE),
('Trine Ronning', TRUE),
('Nadine Angerer', TRUE),
('Christine Sinclair', TRUE),
('Abby Erceg', TRUE),
('Millie Bright', TRUE),
('Sam Kerr', TRUE),
('Millie Bright', TRUE),
('Kosovare Asllani', TRUE),
('Wendie Renard', TRUE),
('Catalina Usme', TRUE),
('Sherida Spitse', TRUE),
('Kosovare Asllani', TRUE),
('Khadija Shaw', TRUE),
('Ghizlane Chebbak', TRUE),
('Chiamaka Nnadozie', TRUE),
('Pernille Harder', TRUE),
('Thembi Kgatlana', TRUE),
('Lindsey Horan', TRUE),
('Esther Gonzalez', TRUE),
('Maren Mjelde', TRUE),
('Daniela Montoya', TRUE),
('Alexandra Popp', TRUE),
('Barbara Bonansea', TRUE),
('Caroline Seger', TRUE),
('Marta', TRUE),
('Grace Geyoro', TRUE),
('Sherida Spitse', TRUE),
('Lindsey Horan', TRUE),
('Pernille Harder', TRUE),
('Millie Bright', TRUE),
('Olga Carmona', TRUE),
('Barbra Banda', TRUE),
('Chiamaka Nnadozie', TRUE),
('Steph Catley', TRUE),
('Ghizlane Chebbak', TRUE),
('Ali Riley', TRUE),
('Hali Long', TRUE),
('Daniela Montoya', TRUE),
('Barbara Bonansea', TRUE),
('Rafaelle', TRUE),
('Allyson Swaby', TRUE),
('Refiloe Jane', TRUE),
('Pernille Harder', TRUE),
('Nerilia Mondesir', TRUE),
('Sherida Spitse', TRUE),
('Huynh Nhu', TRUE),
('Chiamaka Nnadozie', TRUE),
('Katherine Alvarado', TRUE),
('Barbra Banda', TRUE),
('Katie McCabe', TRUE),
('Kim Hye-ri', TRUE),
('Hali Long', TRUE),
('Maren Mjelde', TRUE),
('Vanina Correa', TRUE),
('Ghizlane Chebbak', TRUE),
('Natalia Mills', TRUE),
('Refiloe Jane', TRUE),
('Dolores Silva', TRUE),
('Khadija Shaw', TRUE),
('Huynh Nhu', TRUE),
('Saki Kumagai', TRUE),
('Nerilia Mondesir', TRUE),
('Wang Shanshan', TRUE),
('Christine Sinclair', TRUE),
('Lia Walti', TRUE),
('Katherine Alvarado', TRUE),
('Maren Mjelde', TRUE),
('Katie McCabe', TRUE),
('Sari van Veenendaal', TRUE),
('Caroline Seger', TRUE),
('Caroline Seger', TRUE),
('Alex Morgan', TRUE),
('Sari van Veenendaal', TRUE),
('Caroline Seger', TRUE),
('Alex Morgan', TRUE),
('Steph Houghton', TRUE),
('Wu Haiyan', TRUE),
('Saki Kumagai', TRUE),
('Megan Rapinoe', TRUE),
('Christine Sinclair', TRUE),
('Gabrielle Onguene', TRUE),
('Marta', TRUE),
('Desire Oparanozie', TRUE),
('Sam Kerr', TRUE),
('Christine Sinclair', TRUE),
('Ali Riley', TRUE),
('Alex Morgan', TRUE),
('Christiane Endler', TRUE),
('Steph Houghton', TRUE),
('Estefania Banini', TRUE),
('Marta', TRUE),
('Sam Kerr', TRUE),
('Alexandra Popp', TRUE),
('Irene Paredes', TRUE),
('Maren Mjelde', TRUE),
('Amandine Henry', TRUE),
('Kanjana Sungngoen', TRUE),
('Christiane Endler', TRUE),
('Christine Manie', TRUE),
('Ali Riley', TRUE),
('Rachel Corsie', TRUE),
('Sara Gama', TRUE),
('Estefania Banini', TRUE),
('Marta', TRUE),
('Wu Haiyan', TRUE),
('Cho So-hyun', TRUE),
('Marta Torrejon', TRUE),
('Maren Mjelde', TRUE),
('Sari van Veenendaal', TRUE),
('Caroline Seger', TRUE),
('Kanjana Sungngoen', TRUE),
('Saki Kumagai', TRUE),
('Christine Manie', TRUE),
('Sara Gama', TRUE),
('Konya Plummer', TRUE),
('Rachel Corsie', TRUE),
('Wu Haiyan', TRUE),
('Janine van Wyk', TRUE),
('Desire Oparanozie', TRUE),
('Cho So-hyun', TRUE),
('Aya Miyama', TRUE),
('Steph Houghton', TRUE),
('Steph Houghton', TRUE),
('Nadine Angerer', TRUE),
('Aya Miyama', TRUE),
('Christine Sinclair', TRUE),
('Wendie Renard', TRUE),
('Carli Lloyd', TRUE),
('Mandy van den Berg', TRUE),
('Steph Houghton', TRUE),
('Natalia Gaitan', TRUE),
('Lisa De Vanna', TRUE),
('Caroline Abbe', TRUE),
('Cho So-hyun', TRUE),
('Caroline Seger', TRUE),
('Christine Manie', TRUE),
('Maurine Dorneles Goncalves', TRUE),
('Natalia Gaitan', TRUE),
('Wendie Renard', TRUE),
('Veronica Boquete', TRUE),
('Christine Manie', TRUE),
('Aya Miyama', TRUE),
('Abby Wambach', TRUE),
('Lotta Schelin', TRUE),
('Nadine Angerer', TRUE),
('Ingrid Hjelmseth', TRUE),
('Abby Erceg', TRUE),
('Christine Sinclair', TRUE),
('Natalia Gaitan', TRUE),
('Veronica Boquete', TRUE),
('Nayeli Rangel', TRUE),
('Shirley Cruz', TRUE),
('Evelyn Nwabuoku', TRUE),
('Nancy Aguilar', TRUE),
('Christine Manie', TRUE),
('Lotta Schelin', TRUE),
('Mandy van den Berg', TRUE),
('Ingrid Hjelmseth', TRUE),
('Duangnapa Sritala', TRUE),
('Abby Erceg', TRUE),
('Steph Houghton', TRUE),
('Shirley Cruz', TRUE),
('Nayeli Rangel', TRUE),
('Cho So-hyun', TRUE),
('Evelyn Nwabuoku', TRUE),
('Ligia Moreira', TRUE),
('Lisa De Vanna', TRUE),
('Caroline Abbe', TRUE),
('Duangnapa Sritala', TRUE),
('Dominique Thiamale', TRUE),
('Wu Haiyan', TRUE),
('Mandy van den Berg', TRUE);